apiVersion: v1
kind: Namespace
metadata:
  name: webapps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpeg2avif
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpeg2avif
  template:
    metadata:
      labels:
        app: jpeg2avif
    spec:
      containers:
        - name: jpeg2avif
          image: ghcr.io/ekskog/jpeg2avif-web:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 900  # Every 15 minutes
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 900  # Every 15 minutes
            timeoutSeconds: 3
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: jpeg2avif
  namespace: webapps
spec:
  selector:
    app: jpeg2avif
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
